### ISSUE TITLE
Fix the "no module named osgeo" issue

### ISSUE THREAD

**Issue by vascobnunes** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#51]
Traceback (most recent call last):
  File "c:\users\vbnunes\appdata\local\continuum\miniconda3\envs\vasco\lib\site-packages\fels\fels.py", line 23, in <module>
    from osgeo import gdal
ModuleNotFoundError: No module named 'osgeo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vbnunes\appdata\local\continuum\miniconda3\envs\vasco\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vbnunes\appdata\local\continuum\miniconda3\envs\vasco\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vbnunes\AppData\Local\Continuum\miniconda3\envs\vasco\Scripts\fels.exe\__main__.py", line 4, in <module>
  File "c:\users\vbnunes\appdata\local\continuum\miniconda3\envs\vasco\lib\site-packages\fels\fels.py", line 26, in <module>
    (recommended) use: conda config --add channels conda-forge && conda install gdal""")
ImportError: Could not find the GDAL/OGR Python library bindings. Using conda (recommended) use: conda config --add channels conda-forge && conda install gdal

**Comment by Erotemic** [comment]
Using the latest gdal 3.4.0 from conda forge should solve this issue.
